### PR TITLE
Kbiery/df tp stream

### PR DESCRIPTION
**Pull request by wesketchum**
Making this pull request to serve as the main hub for TimeSlice changes. Some of the todos (some may be done?):

- [x] https://github.com/DUNE-DAQ/dfmodules/pull/144 merged onto it
- [x] Additional renaming in hdf5libs of the basic parameters (trigger_record --> record)
- [x] Passing through configuration information rather than having hardcoded config pieces
- [ ] TimeSlice writing unit tests

PRs that should be merged with this one:
* https://github.com/DUNE-DAQ/daqconf/pull/12
* https://github.com/DUNE-DAQ/hdf5libs/pull/10

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
As noted in the commit list, I've committed changes to dfmodules:kbiery/df_tp_stream and daqconf:kbiery/df_tp_stream first-pass changes to include the appropriate config params for TPStreamWriter.

**Comment by wesketchum** [comment]
I've updated the file layout parameter naming in hdf5libs, and updated the configurations in the daqconf branch. Have made a PR draft for the daqconf changes: https://github.com/DUNE-DAQ/daqconf/pull/12.

One thing to discuss is the use of slice number as the 'trigger number' in the fragment. There are workarounds we could do in hdf5libs to avoid this, but that may also be a little hacky...

**Comment by wesketchum** [comment]
Everything builds for me (with appropriate `hdflibs` and `daqconf` packages) on the 03-08 nightly. Ran an integration test with this config:

```
daqconf_multiru_gen --host-ru localhost --host-ru localhost --host-df localhost --host-df localhost --host-tpw localhost -d $PWD/frames.bin -o . -s 10 -n 2 --enable-tpset-writing --enable-software-tpg mdapp_2x2_swtpg
```

And saw files for both TriggerRecords and TimeSlices.

**Review by bieryAtFnal — APPROVED** [review]
LGTM

**Pull request merged**
