### PR TITLE
Use sequence number - first step

### PR DESCRIPTION
**Pull request by mroda88**

### CODE REVIEW

**Comment by mroda88** [comment]
A draft of the slicing is ready to have a look at and decide if we like it. 

I would prefer if first we merged the Timeout branch. The two are clearly interfering and once the other is merged the logic of this branch will need to be tweaked. 

There is one item I would like some feedback on. If in the sequencing procedure we end up in a slice with no requests shall we create an empty TR in the disk? Or shall we simply leave a hole in the sequence?

**Comment by bieryAtFnal** [comment]
Marco, I had some success in testing the code on this branch (In conjunction with "AddSequenceNumber" branches in other repos), and I wanted to commit the minimal changes that I needed to make in the data-writing code to get things to work.  I hope that this was OK.

Looking ahead, I think that we can merge the AddSequenceNumber changes in _dataformats and dfmessages_ to their respective _develop_ branches, move forward with Phil's changes to _trigger and minidaqapp_ to allow us to specify the readout window in the _trigger_ configuration, make a one-line change in _readout_ to set the Fragment sequence_number from the DataRequest sequence_number, then re-test and merge these changes in _dfmodules_.

**Comment by mroda88** [comment]
Example of test. I configured the system to generate trigger decisions from -1000 to 1000 from the trigger timestamp. And I told the system to have a maximum of 800 ticks data requests. 
The output of the file is (shortened)
```
Path                          :	TriggerRecord00036.0/TriggerRecordHeader
Version                       : 2
Trigger number                : 36
Trigger timestamp             : 79759096968881318 (2020-07-19 20:05:39.377626)
No. of requested components   : 2
---------------------------------------------------
Path                          :	TriggerRecord00036.0/TPC/APA000/Link00
Version                       : 3
Frag Size                     : 16784
Trig timestamp                : 79759096968881318 (2020-07-19 20:05:39.377626)
Window begin                  : 79759096968880318 (2020-07-19 20:05:39.377606)
Window end                    : 79759096968881118 (2020-07-19 20:05:39.377622)
---------------------------------------------------
Path                          :	TriggerRecord00036.1/TPC/APA000/Link00
Version                       : 3
Frag Size                     : 22352
Trig timestamp                : 79759096968881318 (2020-07-19 20:05:39.377626)
Window begin                  : 79759096968881118 (2020-07-19 20:05:39.377622)
Window end                    : 79759096968881918 (2020-07-19 20:05:39.377638)
---------------------------------------------------
Path                          :	TriggerRecord00036.2/TPC/APA000/Link00
Version                       : 3
Frag Size                     : 11216
Trig timestamp                : 79759096968881318 (2020-07-19 20:05:39.377626)
Window begin                  : 79759096968881918 (2020-07-19 20:05:39.377638)
Window end                    : 79759096968882318 (2020-07-19 20:05:39.377646)
```
You can see that the first sequence has with width 800, so does the second and the last has width 400. Distance from the trig timestamp is expected. 
The same behaviour is observed for link01 as well.

I take it like the algorithm is working. 
The only pending question is: do we want to monitor this splitting with some dedicated metric? If yes, what are we interested in?

**Comment by bieryAtFnal** [comment]
I've run two tests.  In both of the tests, the readout window for the first RU is

- -100000 to +100000

and the readout window for the second RU is

- -80000 to +120000

With a setting of max_time_window to zero, I see the expected behavior in the raw data.  That is, the timestamps for the two Fragments are slightly offset:

```
================================================================================
Path                          :	TriggerRecord00031/TriggerRecordHeader
Size                          :	(128, 1)
Data type                     :	int8
Magic word                    : 0x33334444
Version                       : 2
Trigger number                : 31
Trigger timestamp             : 79759095230642398 (2020-07-19 13:05:04.612848)
No. of requested components   : 2
Run Number                    : 1837
Error bits                    : 0
Trigger type                  : 1
--------------------------------------------------------------------------------
Path                          :	TriggerRecord00031/TPC/APA000/Link00
Size                          :	(3712080, 1)
Data type                     :	int8
Magic word                    : 0x11112222
Version                       : 3
Frag Size                     : 3712080
Trig number                   : 31
Trig timestamp                : 79759095230642398 (2020-07-19 13:05:04.612848)
Window begin                  : 79759095230542398 (2020-07-19 13:05:04.610848)
Window end                    : 79759095230742398 (2020-07-19 13:05:04.614848)
Run number                    : 1837
Error bits                    : 0
Fragment type                 : 1
GeoID type                    : TPC
GeoID region                  : 0
GeoID element                 : 0
--------------------------------------------------------------------------------
Path                          :	TriggerRecord00031/TPC/APA000/Link01
Size                          :	(3712080, 1)
Data type                     :	int8
Magic word                    : 0x11112222
Version                       : 3
Frag Size                     : 3712080
Trig number                   : 31
Trig timestamp                : 79759095230642398 (2020-07-19 13:05:04.612848)
Window begin                  : 79759095230562398 (2020-07-19 13:05:04.611248)
Window end                    : 79759095230762398 (2020-07-19 13:05:04.615248)
Run number                    : 1837
Error bits                    : 0
Fragment type                 : 1
GeoID type                    : TPC
GeoID region                  : 0
GeoID element                 : 1
```

WIth a setting of max_time_window to 250000, I see the offset windows somehow get lost:

```
================================================================================
Path                          :	TriggerRecord00031/TriggerRecordHeader
Size                          :	(128, 1)
Data type                     :	int8
Magic word                    : 0x33334444
Version                       : 2
Trigger number                : 31
Trigger timestamp             : 79759095230672293 (2020-07-19 13:05:04.613446)
No. of requested components   : 2
Run Number                    : 1840
Error bits                    : 0
Trigger type                  : 1
--------------------------------------------------------------------------------
Path                          :	TriggerRecord00031/TPC/APA000/Link00
Size                          :	(3712080, 1)
Data type                     :	int8
Magic word                    : 0x11112222
Version                       : 3
Frag Size                     : 3712080
Trig number                   : 31
Trig timestamp                : 79759095230672293 (2020-07-19 13:05:04.613446)
Window begin                  : 79759095230572293 (2020-07-19 13:05:04.611446)
Window end                    : 79759095230772293 (2020-07-19 13:05:04.615446)
Run number                    : 1840
Error bits                    : 0
Fragment type                 : 1
GeoID type                    : TPC
GeoID region                  : 0
GeoID element                 : 0
--------------------------------------------------------------------------------
Path                          :	TriggerRecord00031/TPC/APA000/Link01
Size                          :	(3712080, 1)
Data type                     :	int8
Magic word                    : 0x11112222
Version                       : 3
Frag Size                     : 3712080
Trig number                   : 31
Trig timestamp                : 79759095230672293 (2020-07-19 13:05:04.613446)
Window begin                  : 79759095230592293 (2020-07-19 13:05:04.611846)
Window end                    : 79759095230792293 (2020-07-19 13:05:04.615846)
Run number                    : 1840
Error bits                    : 0
Fragment type                 : 1
GeoID type                    : TPC
GeoID region                  : 0
GeoID element                 : 1
```

I don't understand why they wouldn't be different in both cases...

**Comment by bieryAtFnal** [comment]
Ah, sorry Marco.  I see now that the numbers in my previous post **did** look good.  Thanks for pointing that out.
I'll next run a similar test with a smaller max_time_window and offset request times, but given our conversation, I expect to get the expected results.
Thanks,
KB

**Comment by bieryAtFnal** [comment]
The results of the test with an offset between the two DataRequests **and** with a max_time_window smaller than the TriggerDecision request windows looked good.

I updated the hdf5_dump.py script to include the printout of the sequence numbers from the TRheader and the FragmentHeader.

**Review by bieryAtFnal — APPROVED** [review]
LGTM

**Pull request merged**
