### PR TITLE
Integration test for mdapp args

### PR DESCRIPTION
**Pull request by plasorak**
This PR will only work with https://github.com/DUNE-DAQ/integrationtest/pull/15 the `config_arguments_test.py` goes through all the arguments and check that they have an effect on the JSON. It also checks that the minidaqapp logs are error-free (and it takes a while to run...)

### CODE REVIEW

**Comment by philiprodrigues** [comment]
I ran this test and it looks OK: for a config parameter that is used, the test passes. I hacked minidaqapp so that one of the command line parameters is unused, and the corresponding test fails. @bieryAtFnal do you want to take a look before we merge this?

**Comment by eflumerf** [comment]
I'm concerned that this test isn't portable. I'm getting some worrying output from the test:
```
================================================================================================================================== short test summary info ===================================================================================================================================
FAILED sourcecode/dfmodules/integtest/config_arguments_test.py::test_json_log[control-hsi-hw-run_nanorc0] - AssertionError: assert False
FAILED sourcecode/dfmodules/integtest/config_arguments_test.py::test_json_log[use-hsi-hw-run_nanorc0] - AssertionError: assert False
FAILED sourcecode/dfmodules/integtest/config_arguments_test.py::test_json_log[trigger-candidate-config-run_nanorc0] - AssertionError: assert False
FAILED sourcecode/dfmodules/integtest/config_arguments_test.py::test_json_log[control-timing-partition-run_nanorc0] - AssertionError: assert False
FAILED sourcecode/dfmodules/integtest/config_arguments_test.py::test_json_log[enable-software-tpg-run_nanorc0] - AssertionError: assert False
FAILED sourcecode/dfmodules/integtest/config_arguments_test.py::test_json_log[enable-tpset-writing-run_nanorc0] - AssertionError: assert False
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_conf_arg_effect[control-hsi-hw-run_nanorc0] - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-eflumerf/pytest-26/json26'
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_conf_arg_effect[hsi-re-mask-run_nanorc0] - Failed
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_json_log[hsi-re-mask-run_nanorc0] - Failed
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_conf_arg_effect[hsi-fe-mask-run_nanorc0] - Failed
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_json_log[hsi-fe-mask-run_nanorc0] - Failed
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_conf_arg_effect[hsi-inv-mask-run_nanorc0] - Failed
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_json_log[hsi-inv-mask-run_nanorc0] - Failed
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_conf_arg_effect[hsi-source-run_nanorc0] - Failed
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_json_log[hsi-source-run_nanorc0] - Failed
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_conf_arg_effect[use-hsi-hw-run_nanorc0] - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-eflumerf/pytest-26/json33'
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_conf_arg_effect[enabled-hsi-signals-run_nanorc0] - Failed
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_json_log[enabled-hsi-signals-run_nanorc0] - Failed
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_conf_arg_effect[trigger-candidate-config-run_nanorc0] - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-eflumerf/pytest-26/json42'
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_conf_arg_effect[control-timing-partition-run_nanorc0] - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-eflumerf/pytest-26/json43'
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_conf_arg_effect[timing-partition-trigger-mask-run_nanorc0] - Failed
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_json_log[timing-partition-trigger-mask-run_nanorc0] - Failed
ERROR sourcecode/dfmodules/integtest/config_arguments_test.py::test_conf_arg_effect[enable-tpset-writing-run_nanorc0] - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytest-of-eflumerf/pytest-26/json68'
==================================================================================================================== 6 failed, 135 passed, 17 errors in 966.75s (0:16:06) ====================================================================================================================
```

**Comment by eflumerf** [comment]
As an update to my last comment, having thought about it more, there are very good reasons for having tests which depend on the actual hardware which we need the software to work with. Such tests should verify that the hardware in question is actually available and inform the user if it isn't.

**Comment by dingp** [comment]
Is the PR still up-to-date with all the changes in other repos happened since March?

**Comment by bieryAtFnal** [comment]
We should probably defer this to v3.1.0, but I'd vote that we don't delete it until we have a chance to look into it more.

**Comment by plasorak** [comment]
This is probably not the correct way to do this. First off these should be inside `daqconf`, and also it should be automated. Closing for now.

**Pull request closed without merging**
