### PR TITLE
Feature/style guide

### PR DESCRIPTION
**Pull request by carloschavez**
Done running  linter and clang-tiddy in all the dfmodules tree directory 

linter :   Fixed warning messages, some  unsigned 32 int declarations have been suppressed (//NOLINT) 
clan-tidy : constructors in  include/dfmodules/StorageKey.hpp  need fixing , ignonred message for the moment with //NOLINT

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
Everything seems to compile and run as expected (including unit tests).

However, when I checked a few files to see if clang-format suggested any changes, I found that it did.
For example:

```
check_clang_format DataWriter.cpp 
22a23
> #include <algorithm>
24a26
> #include <memory>
27d28
< #include <vector>
29,30c30
< #include <memory>
< #include <algorithm>
---
> #include <vector>
185,186c185,187
<       int number_of_32bit_values_to_print = std::min((number_of_32bit_values_per_row * max_number_of_rows),
<                                                      (static_cast<size_t>(frag_ptr->get_size()) / sizeof(uint32_t))); // NOLINT
---
>       int number_of_32bit_values_to_print =
>         std::min((number_of_32bit_values_per_row * max_number_of_rows),
>                  (static_cast<size_t>(frag_ptr->get_size()) / sizeof(uint32_t)));               // NOLINT
```

Is this expected?  Sorry if I'm doing something wrong.  `check_clang_format` is a simple script that I wrote to run clang-format.

**Comment by carloschavez** [comment]
Hi Kurt,  
Thanks for pointing this out,  my own clang-format script wasn't actually working as it isn't recognizing the .clang-format file provided in  daq-buildtools/configs/.clang-format

So basically, it was not running clang-format at all
Do you have a valid .clang-format  file ?

**Comment by bieryAtFnal** [comment]
I usually copy the .clang-format file from daq-buildtools/configs into the /sourcecode directory of my working area...  Not sure if that is the right model.

**Comment by carloschavez** [comment]
Hi Kurt,  I found the problem that I was having. 
Recent changes in .dunedaq_area  removed  the dependency on clang :      "clang v7_0_0rc3 e19:prof"
Then I was using clang-format from my system which has a very old version of LLVM installed, hence I was getting an error telling me that .clang-format file was invalid .  

Now I have included  "clang v7_0_0rc3 e19:prof"  in .dunedaq_area and  I am picking up the correct version of clang-format and all is working fine with my script.

I should be able to push  all my clang-format changes  after I run some test.

**Comment by carloschavez** [comment]
The commit that includes clang-format changes is 77023ab  : 
https://github.com/DUNE-DAQ/dfmodules/pull/14/commits/77023abc9cac7a42a4daaf88c2351667efb06e48
Kurt, please feel free to close this PR,  or Merge  it into develop and then I make a new PR for the clang-format changes.
whatever is easier.

**Pull request merged**
