### PR TITLE
ta's are not stored in readout app

### PR DESCRIPTION
**Pull request by glehmannmiotto**

### CODE REVIEW

**Review by eflumerf — APPROVED** [review]
I generally lean towards deleting code and letting Git handle it, but this is fine for a quick fix.

**Comment by glehmannmiotto** [comment]
code removed and better check introduced on tp generation.

**Comment by eflumerf** [comment]
I don't think you pushed, since this appears to be unchanged since I commented last.

**Review by eflumerf — APPROVED** [review]
Unit tests and a simple test-session run look good

**Pull request merged**
