### PR TITLE
Desired error behaviour

### PR DESCRIPTION
**Pull request by mroda88**
possible solution for #30

### CODE REVIEW

**Comment by mroda88** [comment]
Note that I added a missing addition from Ron in cmake/dfmodulesConfig.cmake.in

**Comment by bieryAtFnal** [comment]
Marco, thanks for adding that entry in cmake/dfmodulesConfig.cmake.in!

**Comment by bieryAtFnal** [comment]
The changes look good to me.  I made a couple of additional changes, please check them:  I ran clang-format, and I added a try/catch around open_file_if_needed calls in HDF5DataStore.hpp.

The reason for the latter:  as part of my testing, I specified a bogus output path ("/abc").  With this, HDF5DataStore and DataWriter correctly threw an exception at Start time that complained that it was a bogus path.  That was all good.
To test how one type of write() error might be handled, I then commented out that check of the output path at Start time.  With that, I noticed an uncaught std::exception from the HighFive code when it tried to open a new file at the bogus path during a write() call.  To protect against this, I added the try/catch.

**Comment by mroda88** [comment]
Good catches! I'll have a look before the meeting today

**Review by bieryAtFnal — APPROVED** [review]
These changes look good to me.

**Pull request merged**
