### PR TITLE
integtest event count

### PR DESCRIPTION
**Pull request by bieryAtFnal**
In an attempt to provide additional validity checking in several of the integration tests that we have in dfmodules/integtest, I've added validation of the expected number of trigger records.

The test generally succeeds, but I suspect that there may be some computers on which the event rate is low (because of a lack of sufficient resources). 

However, I'm submitting these changes as a pull request to get them reviewed by others, and if approved, to make them available for others to use in testing.

### CODE REVIEW

**Review by eflumerf — COMMENTED** [review]
Would it be better to define "expected event count" and "tolerance" for the check_event_count check?

**Review by philiprodrigues — APPROVED** [review]
Sorry for the delay in reviewing. This looks good to me too, though I agree with @eflumerf that expected/tolerance might be a little nicer than min/max (but either works)

**Comment by bieryAtFnal** [comment]
Eric or Phil, I changed the "event count" check to use 'expected value' and 'tolerance', as you suggested.  Could one of you re-confirm that the changes look OK?  Then we can do the merge.
Thanks,
Kurt

**Review by eflumerf — APPROVED** [review]
LGTM

**Pull request merged**
