### PR TITLE
bring hdf5_dump to the latest dataformats version (with new GeoID)

### PR DESCRIPTION
**Pull request by dingp**
This is to implement features described in #75.

A few highlights:

1. In `print_header_dict()` function, there is now a `filtered_list` containing a list of fields to be suppressed in the output. It contains any 'padding', and versions of `GeoID` or `Component Request`;
2. A new function `get_geo_id_type()` is added to translate `Geo ID type` from integer to string;
3. Field names `GeoID (APA)` and `GeoID (link)` are replaced with `GeoID region` and `GeoID element` in the output.

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
Pengfei, thanks for these updates.

I noticed an oddity with one of the GeoID region numbers in the printout from this new version.  An example is included below.  I believe that the second fragment should have GeoID region of 0 and element of 1, instead of the 65536 and 0 that are shown.

```
Path                          :	TriggerRecord00031/TriggerRecordHeader
Size                          :	(128, 1)
Data type                     :	int8
Magic word                    : 0x33334444
Version                       : 1
Trigger number                : 31
Trigger timestamp             : 79759095231313043 (2020-07-19 13:05:04.626261)
No. of requested components   : 2
Run Number                    : 111
Error bits                    : 0
Trigger type                  : 1
--------------------------------------------------------------------------------
GeoID type                    : TPC
GeoID region                  : 0
GeoID element                 : 0
Begin time                    : 79759095231313043 (2020-07-19 13:05:04.626261)
End time                      : 79759095231314043 (2020-07-19 13:05:04.626281)
--------------------------------------------------------------------------------
GeoID type                    : TPC
GeoID region                  : 65536
GeoID element                 : 0
Begin time                    : 79759095231313043 (2020-07-19 13:05:04.626261)
End time                      : 79759095231314043 (2020-07-19 13:05:04.626281)
--------------------------------------------------------------------------------
Path                          :	TriggerRecord00031/TPC/APA000/Link00
Size                          :	(22352, 1)
Data type                     :	int8
Magic word                    : 0x11112222
Version                       : 2
Frag Size                     : 22352
Trig number                   : 31
Trig timestamp                : 79759095231313043 (2020-07-19 13:05:04.626261)
Window begin                  : 79759095231313043 (2020-07-19 13:05:04.626261)
Window end                    : 79759095231314043 (2020-07-19 13:05:04.626281)
Run number                    : 111
Error bits                    : 0
Fragment type                 : 1
GeoID type                    : TPC
GeoID region                  : 0
GeoID element                 : 0
--------------------------------------------------------------------------------
Path                          :	TriggerRecord00031/TPC/APA000/Link01
Size                          :	(22352, 1)
Data type                     :	int8
Magic word                    : 0x11112222
Version                       : 2
Frag Size                     : 22352
Trig number                   : 31
Trig timestamp                : 79759095231313043 (2020-07-19 13:05:04.626261)
Window begin                  : 79759095231313043 (2020-07-19 13:05:04.626261)
Window end                    : 79759095231314043 (2020-07-19 13:05:04.626281)
Run number                    : 111
Error bits                    : 0
Fragment type                 : 1
GeoID type                    : TPC
GeoID region                  : 65536   <<<<< unexpected value
GeoID element                 : 0     <<<<< unexpected value
```

**Comment by dingp** [comment]
I misplaced two characters in the formatting string, which resulted in decoding the `region ID` as `uint32_t` and `element ID` as `uint16_t `. While in fact, `region ID` is `uint16_t` and `element ID` is `uint32_t`.

It is fixed now. Please give it another try.

**Comment by mroda88** [comment]
I also see all good. This is my test from this morning:
```bash
================================================================================
Path                          :	TriggerRecord00054/TriggerRecordHeader
Size                          :	(128, 1)
Data type                     :	int8
Magic word                    : 0x33334444
Version                       : 1
Trigger number                : 54
Trigger timestamp             : 79759095346539368 (2020-07-19 20:05:06.930787)
No. of requested components   : 2
Run Number                    : 0
Error bits                    : 0
Trigger type                  : 1
--------------------------------------------------------------------------------
Path                          :	TriggerRecord00054/TPC/APA000/Link00
Size                          :	(22352, 1)
Data type                     :	int8
Magic word                    : 0x11112222
Version                       : 2
Frag Size                     : 22352
Trig number                   : 54
Trig timestamp                : 79759095346539368 (2020-07-19 20:05:06.930787)
Window begin                  : 79759095346539368 (2020-07-19 20:05:06.930787)
Window end                    : 79759095346540368 (2020-07-19 20:05:06.930807)
Run number                    : 0
Error bits                    : 0
Fragment type                 : 1
GeoID type                    : TPC
GeoID region                  : 0
GeoID element                 : 0
--------------------------------------------------------------------------------
Path                          :	TriggerRecord00054/TPC/APA000/Link01
Size                          :	(22352, 1)
Data type                     :	int8
Magic word                    : 0x11112222
Version                       : 2
Frag Size                     : 22352
Trig number                   : 54
Trig timestamp                : 79759095346539368 (2020-07-19 20:05:06.930787)
Window begin                  : 79759095346539368 (2020-07-19 20:05:06.930787)
Window end                    : 79759095346540368 (2020-07-19 20:05:06.930807)
Run number                    : 0
Error bits                    : 0
Fragment type                 : 1
GeoID type                    : TPC
GeoID region                  : 0
GeoID element                 : 1

```

**Review by bieryAtFnal — APPROVED** [review]
LGTM

**Pull request merged**
