### PR TITLE
Add python config for two-process application

### PR DESCRIPTION
**Pull request by philiprodrigues**
This PR adds a python script that produces the json configs needed to run a fake MiniDAQApp as two processes: one containing the TriggerDecisionEmulator and one containing everything else. The "fake" here means that there are no readout modules in the config: the fragments are provided by the FakeDataProd module from dfmodules.

There's also a python script to generate a config that's the same as `testapp_noreadout_confgen.py` but with pairs of `QueueToNetwork`/`NetworkToQueue` modules inserted in the connections with the `TriggerDecisionEmulator`. This is all still in one process, so its only purpose is to test the `QueueToNetwork`/`NetworkToQueue` functionality

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
I've compared the resulting data files from 

- testapp_noreadout_confgen.py, and 
- testapp_noreadout_networkqueue_confgen.py

and they are equivalent.  One request might be to reduce the verbosity of the ZmqSenderImpl  messages...

Also, testapp_noreadout_confgen.py has moved ahead of testapp_noreadout_networkqueue_confgen.py a bit (for example, with the ability to disable data writing).  Would it be worth adding those changes to testapp_noreadout_networkqueue_confgen.py?  I can help with that.

I'll look at testapp_noreadout_two_process.py next...

**Comment by bieryAtFnal** [comment]
Same comments about testapp_noreadout_two_process.py: output file looks great, should we add disable_data_storage, etc.

**Comment by philiprodrigues** [comment]
I agree that merging changes from `testapp_noreadout_confgen.py` into the other two configs is a good idea. If you have time to do that, that would be great (if you don't have time, I can add it to my todo list)

**Comment by bieryAtFnal** [comment]
I will work on copying the recent additions from testapp_noreadout_confgen.py into the other two.

**Comment by bieryAtFnal** [comment]
I believe that I have successfully added the --disable-data-storage command-line argument to testapp_noreadout_networkqueue_confgen.py and testapp_noreadout_two_process.py.

While I was making changes, I modified the default names of the resulting JSON files for all three python files.  If this change is undesirable, I can change that back.

**Comment by philiprodrigues** [comment]
Thanks for the update. Works in my local tests.

**Pull request merged**
